### ISSUE TITLE
Line draws for all even with sessionid passed

### ISSUE THREAD

**Issue by ManjTi** [dceejay/RedMap#233]
Example msg to [worldmap](https://www.npmjs.com/package/node-red-contrib-web-worldmap) node:

`{"payload":{"name":"line42","weight":2,"line":[[60.84769,27.128244],[60.792881,27.281022]],"dashArray":"0 0","layer":"Salq's track","color":"#808080"},"_sessionid":"bc5a2fc6-e9e6-4038-a429-d4b0e23a8cea","_sessionip":"192.168.16.8","_msgid":"3a201521839fb918"}`

The line appears on screen of target session, but when I open url on (for example) my mobile device, it loads too.

Added:
It stays after reload of page too.

**Comment by meeki007** [comment]
I hate to say : “it's no longer a bug once your user base incorporates a behavior into their code, it's a feature”

Worldmap is event driven. If you want to only allow a specific user access to the data/line/point ... etc you need to track that user.
I use a [JWT](https://jwt.io/) to track specific client and tie it to his _sessionid tracker when they login. With some out of the box thinking you can even create user login directly in world map.
![Screenshot from 2023-05-25 13-56-41](https://github.com/dceejay/RedMap/assets/5952964/5b7f2865-f2ad-4a43-b3f2-574dd5172d17)

Where do I store the JWT? 
1) In the parameters of the client url. MAKE SURE you encrypt it before sending it.

This leads into
```
msg.payload = { 
    "command": 
        { "clear": "your_layer_name" } 
};
```
You can clear layers upon connection of a new client that is not suppose to see something. I use it mainly to clear the custom-popup I keep in Antarctica that I send users to for custom dialog messages.

Why is there not a howto on any of this?
Its hard todo and is very specific to the method your using or the data your trying to display. ALSO SECURITY!!! I cant having the ins and out of my login system posted on the internet and rewriting all the functions for a working example would take a few weeks of work that is unpaid.

@dceejay If you go down the path of stateful data for woldmap please make a tick box so those of us who don't need or want it can opt out.  I am not against this functionality for new users. As the barrier can be high for them. however I does sound like allot of work to implement.

**Comment by meeki007** [comment]
> So the two options we have are
> Leave it as-is - ie any new connections get all the old data.
> Not save any data that is sent with a _sessionid - so any new sessions will only get old data that has been sent to all (ie without _sessionid set) - and nobody will get any old session specific data. This means that the user would have to handle any specific resend of old data that was specific to any sessions.

I don't think I'm understanding the issue correctly.
I just created a msg.payload testing this issue.
```
msg.payload = { 
    "name": "line42", 
    "weight": 2, 
    "line": [[60.84769, 27.128244], [60.792881, 27.281022]], 
    "dashArray": "0 0", 
    "layer": "Salq's track", 
    "color": "#808080" };
msg._sessionid = 'bc5a2fc6-e9e6-4038-a429-d4b0e23a8cea';
return msg;
```
of course its going to draw the line for anyone who connects. It is going to inject that payload to all as the _sessionid no longer exzists as soon as you hit the deploy button.

I've always wrote a function using context(flow/global) to track all the _sessionid's and then only inject a payload to the current session that triggered the event.

another way of thinking about what I'm doing is:
![Screenshot from 2023-05-25 14-44-32](https://github.com/dceejay/RedMap/assets/5952964/e27e1191-4f9c-49c8-a15d-541f427f7585)

**Comment by dceejay** [comment]
Yes that basically the flow I was also experimenting with. I saved the the _sessionid of (in my case) the last to connect browser - and then sent the message to that browser only... and indeed other already connect browsers don't get the message. But then refreshing any other browser they also get the message - as there is no _sessionid stored in the allPoints array. So currently unless you do manage the sessions actively (as @meeki007 does) then all users will get the data that was supposed to be "private" - and setting up that necessary "security" is non trivial. (also users may not put things one easy to isolate/delete layers)

Re stateless data - once upon a time - in earlier versions - all data was stateless and the user always had to resend any old data... I kept getting requests for late joining clients to see existing markers etc - and it was simple enough to hold allPoints (and time them out) as they arrived - so that functionality was added... 

but now of course - "it's a feature" - so yes - that is my worry. Then again... if I implement making data without a sessionid "global" and held in state and anything with a sessionid stateless and not retained. If you are tracking users by more sensible means like JWT - you could also store any data sent to each in an object keyed by the JWT - then on connection the global data would be sent to all anyway - and any specific data can be sent to the relevant sessionid. I kind of feel that "may" be simpler to manage - but then again I've not actually implemented it so again - feedback appreciated....

**Comment by meeki007** [comment]
**Forward:**
Well this explains allot of my issues with 1k plus lines of code in tons of custom forms (popup) with 250 data points across 8 users needing 100% of my cpu every time the world map loads. Then running tons of clear commands to remove all the data.

My copy of worldmap stays outdated for years until I get a new project and need to do a diff inspection to bring it up to date with my custom code Ive hacked into it to get the job done.
That is why I noticed some things that needed to be added to the documentation last week. --->[https://github.com/dceejay/RedMap/pull/232](https://github.com/dceejay/RedMap/pull/232)

Ive always wanted to get my pull request for redirect  working in woldmap as I always just add it in manually myself. [https://github.com/dceejay/RedMap/pull/174](https://github.com/dceejay/RedMap/pull/174) now that I think of it it does not have to work in an Iframe. I can just put a check to see if its in Iframe and not work if thats the case. note it in the documentation that it will be ignored in in iframe. 

This leads me into wanting to create something for stateless too

**Body:**
The simplest solution would be to create a checkbox on the worldmap[out] node to enable stateless but that does not cover all options a user would want.

I see a need for a drop down instead of a check box. Default would keep everything the same so no breaking changes happen to users flows.

**I would not think about trying to track anything based on sessionid or JWT or anything.** See below solution to the issue my brain came up with. I might be totally wrong on this but its another way of looking at the issue.

! NOTE: I am impartial about naming. Just throwing things at a wall right now to see what sticks. Change suggest anything your like. This is your project Cpt. 

Dropdown Selections
allPoints: all, no sessionid, stateless

Can put it here unless you have a plan for this spot?
![Screenshot from 2023-05-25 18-59-40](https://github.com/dceejay/RedMap/assets/5952964/dc9af9b0-12ea-40cb-ae44-ad4bdb37b52b)

Document the hell out of the feature.
**allPoints: all** - Any and all named "things" plotted on a map will be visible by any user connecting to worldmap with a new _sessionid. This includes a page refresh by user.
**allPoints: no sessionid** - Only plot named "things" to be visible by all users connecting to the worldmap if no _sessionid is supplied in the message.
**allPoints: stateless** - Plotted "things" will not be retained! You must send a msg without a _sessionid to update the worldmap  for all clients connected, or if msg is sent with _sessionid it will update the plot of the "thing" for that specific client. 

I've not spell checked the above ... etc ... this is all me just thinking out loud.

So .... what-cha-think?

**Comment by meeki007** [comment]
I just noticed I would have to explain in the documentation that......
allPoints: no sessionid - In this mode you must plot named "things" for the user if _sessionid is supplied.

why? because anyone who is using _sessionid's to plot things should have the skill or learn the skill to manage the state of thoes named "things" . You can't hold the hand of all users as you will get bloat and buggs and your not microsoft.

**Comment by meeki007** [comment]
I'm going to start work on this now. As I see I need it desperately for my current project / business venture. You provide us enough free things .... and you have no donation link for me to send you beer money.

Also I think this will lower my overhead and the need for all 7 of my dang cluster servers to load the current map.

**Comment by meeki007** [comment]
Testing now: need to add some hard coded msg.outputs so I can really see whats happening. 

```
            if (node.point_retention === "all") {
                if (msg.payload.hasOwnProperty("name")) {
                allPoints[msg.payload.name] = RED.util.cloneMessage(msg.payload);
                var t = node.maxage || 3600;
                if (msg.payload.ttl && msg.payload.ttl < t) { t = msg.payload.ttl; }
                allPoints[msg.payload.name].tout = setTimeout( function() { delete allPoints[msg.payload.name] }, t * 1000 );
                }
            }
            if (node.point_retention === "no_sessionid" && !msg.hasOwnProperty("_sessionid")) {
                if (msg.payload.hasOwnProperty("name")) {
                allPoints[msg.payload.name] = RED.util.cloneMessage(msg.payload);
                var t = node.maxage || 3600;
                if (msg.payload.ttl && msg.payload.ttl < t) { t = msg.payload.ttl; }
                allPoints[msg.payload.name].tout = setTimeout( function() { delete allPoints[msg.payload.name] }, t * 1000 );
                }
            }
```

![Screenshot from 2023-05-25 20-28-48](https://github.com/dceejay/RedMap/assets/5952964/f285ca87-7a35-4a86-92ba-af5b23feef81)

**Comment by meeki007** [comment]
Testing Done!
![Screenshot from 2023-05-26 02-20-40](https://github.com/dceejay/RedMap/assets/5952964/d6502424-22de-4a6d-80e2-d522b7e2c07d)

Looks like it works. I need someone to test it in dashboard as I no longer have a running copy I can test with. If no one can test it by Saturday night in dashboard I'll spin up a VirtualBox and install a fresh copy of node-red with dashboard and do it. Just a tad busy for the next 48hrs.

Putting together a pull request. I will work on documentation next. Please feel free to change any selection names/Icons/etc or fell free to not use this approach if you don't like it. Again this is not my project. Just happy you let me play around with it.

Thanks again @dceejay 

Oh here is the flow so you don't have to create your own test by scratch.
```
[
    {
        "id": "ca4e31bce396a99b",
        "type": "worldmap in",
        "z": "64037268ee27bb53",
        "name": "",
        "path": "/worldmap-test-all",
        "events": "connect,disconnect,point,layer,bounds,files,draw,other",
        "x": 120,
        "y": 60,
        "wires": [
            [
                "08352776167b6380"
            ]
        ]
    },
    {
        "id": "11435c9f314efb38",
        "type": "worldmap",
        "z": "64037268ee27bb53",
        "name": "",
        "lat": "51.50737628967989",
        "lon": "-0.1276536304398657",
        "zoom": "10",
        "layer": "OSMG",
        "cluster": "0",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "none",
        "showgrid": "false",
        "point_retention": "all",
        "showruler": "false",
        "allowFileDrop": "false",
        "path": "/worldmap-test-all",
        "overlist": "DR,CO,RA,DN,HM",
        "maplist": "OSMG,OSMC,EsriC,EsriS,EsriT,EsriDG,UKOS",
        "mapname": "",
        "mapurl": "",
        "mapopt": "",
        "mapwms": false,
        "x": 550,
        "y": 140,
        "wires": []
    },
    {
        "id": "2bbaa29d90a159bb",
        "type": "function",
        "z": "64037268ee27bb53",
        "name": "_sessionid",
        "func": "msg.payload = {\n    \"name\": \"Jason\",\n    \"lat\": 51.50737628967989, \n    \"lon\": -0.1276536304398657\n    }\nmsg._sessionid = '18ddd3e1-e615-46e3-a27d-89c5a9e66f76';\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 120,
        "wires": [
            [
                "11435c9f314efb38",
                "048fd56cd4114665"
            ]
        ]
    },
    {
        "id": "048fd56cd4114665",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 100,
        "wires": []
    },
    {
        "id": "94dd813d3bd0a66d",
        "type": "worldmap in",
        "z": "64037268ee27bb53",
        "name": "",
        "path": "/worldmap-test-no_sessionid",
        "events": "connect,disconnect,point,layer,bounds,files,draw,other",
        "x": 160,
        "y": 200,
        "wires": [
            [
                "af9e03ba9b3d39db"
            ]
        ]
    },
    {
        "id": "5f3e6fdc68877fa5",
        "type": "worldmap",
        "z": "64037268ee27bb53",
        "name": "",
        "lat": "51.50737628967989",
        "lon": "-0.1276536304398657",
        "zoom": "10",
        "layer": "OSMG",
        "cluster": "",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "none",
        "showgrid": "false",
        "point_retention": "no_sessionid",
        "showruler": "false",
        "allowFileDrop": "false",
        "path": "/worldmap-test-no_sessionid",
        "overlist": "DR,CO,RA,DN,HM",
        "maplist": "OSMG,OSMC,EsriC,EsriS,EsriT,EsriDG,UKOS",
        "mapname": "",
        "mapurl": "",
        "mapopt": "",
        "mapwms": false,
        "x": 580,
        "y": 280,
        "wires": []
    },
    {
        "id": "08352776167b6380",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 290,
        "y": 60,
        "wires": []
    },
    {
        "id": "99a18a0f91ab076f",
        "type": "inject",
        "z": "64037268ee27bb53",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 120,
        "wires": [
            [
                "2bbaa29d90a159bb"
            ]
        ]
    },
    {
        "id": "d0f4d07cdc1d5189",
        "type": "worldmap in",
        "z": "64037268ee27bb53",
        "name": "",
        "path": "/worldmap-test-stateless",
        "events": "connect,disconnect,point,layer,bounds,files,draw,other",
        "x": 140,
        "y": 360,
        "wires": [
            [
                "0b909991b2b2f9dd"
            ]
        ]
    },
    {
        "id": "1dc74759efb99bf2",
        "type": "worldmap",
        "z": "64037268ee27bb53",
        "name": "",
        "lat": "51.50737628967989",
        "lon": "-0.1276536304398657",
        "zoom": "10",
        "layer": "OSMG",
        "cluster": "",
        "maxage": "",
        "usermenu": "show",
        "layers": "show",
        "panit": "false",
        "panlock": "false",
        "zoomlock": "false",
        "hiderightclick": "false",
        "coords": "none",
        "showgrid": "false",
        "point_retention": "stateless",
        "showruler": "false",
        "allowFileDrop": "false",
        "path": "/worldmap-test-stateless",
        "overlist": "DR,CO,RA,DN,HM",
        "maplist": "OSMG,OSMC,EsriC,EsriS,EsriT,EsriDG,UKOS",
        "mapname": "",
        "mapurl": "",
        "mapopt": "",
        "mapwms": false,
        "x": 570,
        "y": 440,
        "wires": []
    },
    {
        "id": "d9f0741fed14e4b6",
        "type": "function",
        "z": "64037268ee27bb53",
        "name": "no_sessionid",
        "func": "msg.payload = {\n    \"name\": \"Jason\",\n    \"lat\": 51.50737628967989, \n    \"lon\": -0.1276536304398657\n    }\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 260,
        "wires": [
            [
                "6fb7e6e23e37d01d",
                "5f3e6fdc68877fa5"
            ]
        ]
    },
    {
        "id": "6fb7e6e23e37d01d",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 240,
        "wires": []
    },
    {
        "id": "2842ca62552ebda7",
        "type": "inject",
        "z": "64037268ee27bb53",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 260,
        "wires": [
            [
                "d9f0741fed14e4b6"
            ]
        ]
    },
    {
        "id": "af9e03ba9b3d39db",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 370,
        "y": 200,
        "wires": []
    },
    {
        "id": "26c7362231b8401f",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 510,
        "y": 400,
        "wires": []
    },
    {
        "id": "65436d621e9bb754",
        "type": "inject",
        "z": "64037268ee27bb53",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 420,
        "wires": [
            [
                "8a96ae9c3d125630"
            ]
        ]
    },
    {
        "id": "0b909991b2b2f9dd",
        "type": "debug",
        "z": "64037268ee27bb53",
        "name": "",
        "active": true,
        "tosidebar": true,
        "console": false,
        "tostatus": false,
        "complete": "true",
        "targetType": "full",
        "statusVal": "",
        "statusType": "auto",
        "x": 330,
        "y": 360,
        "wires": []
    },
    {
        "id": "a7b5b74e50752ff0",
        "type": "function",
        "z": "64037268ee27bb53",
        "name": "_sessionid",
        "func": "msg.payload = {\n    \"name\": \"Jason\",\n    \"lat\": 51.50737628967989, \n    \"lon\": -0.1276536304398657\n    }\nmsg._sessionid = '18ddd3e1-e615-46e3-a27d-89c5a9e66f76';\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 300,
        "wires": [
            [
                "6fb7e6e23e37d01d",
                "5f3e6fdc68877fa5"
            ]
        ]
    },
    {
        "id": "3ccc8205e19c2712",
        "type": "inject",
        "z": "64037268ee27bb53",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 300,
        "wires": [
            [
                "a7b5b74e50752ff0"
            ]
        ]
    },
    {
        "id": "8a96ae9c3d125630",
        "type": "function",
        "z": "64037268ee27bb53",
        "name": "no_sessionid",
        "func": "msg.payload = {\n    \"name\": \"Jason\",\n    \"lat\": 51.50737628967989, \n    \"lon\": -0.1276536304398657\n    }\n\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 420,
        "wires": [
            [
                "26c7362231b8401f",
                "1dc74759efb99bf2"
            ]
        ]
    },
    {
        "id": "098f6f4e7d4a9ac6",
        "type": "function",
        "z": "64037268ee27bb53",
        "name": "_sessionid",
        "func": "msg.payload = {\n    \"name\": \"Jason\",\n    \"lat\": 51.50737628967989, \n    \"lon\": -0.1276536304398657\n    }\nmsg._sessionid = '18ddd3e1-e615-46e3-a27d-89c5a9e66f76';\nreturn msg;",
        "outputs": 1,
        "noerr": 0,
        "initialize": "",
        "finalize": "",
        "libs": [],
        "x": 310,
        "y": 460,
        "wires": [
            [
                "26c7362231b8401f",
                "1dc74759efb99bf2"
            ]
        ]
    },
    {
        "id": "74e99bfd2b70743d",
        "type": "inject",
        "z": "64037268ee27bb53",
        "name": "",
        "props": [
            {
                "p": "payload"
            },
            {
                "p": "topic",
                "vt": "str"
            }
        ],
        "repeat": "",
        "crontab": "",
        "once": false,
        "onceDelay": 0.1,
        "topic": "",
        "payload": "",
        "payloadType": "date",
        "x": 120,
        "y": 460,
        "wires": [
            [
                "098f6f4e7d4a9ac6"
            ]
        ]
    }
]
```
