### ISSUE TITLE
Multiple maps

### ISSUE THREAD

**Issue by alima2wolf** [dceejay/RedMap#40]
Hello, 
I am new at this and I am working on the following project:
http://blog.catchpoint.com/2017/12/21/catchpoint-integration-node-red/

I was able to get the nodes placed on the map but we have a lot of test assets. 
I would like to organize them by sports: MLB, NBA, MLS...
I looked at adding a layer but that will not do.
Is there a way to get something like this:

http://52.54.93.114:1880/worldmap/mlb
http://52.54.93.114:1880/worldmap/nba
http://52.54.93.114:1880/worldmap/mls

That will allow us to view the status of our nodes on the worldmap for each sports league.

Thank you in advance.

**Comment by dceejay** [comment]
That's not currently possible - and I can't immediately think of a way to get there.
Will think about it but not promising anything and it won't be short term.
Not sure why layers won't work for you.

**Comment by tve** [comment]
Can you clarify why this is not easy? I took a brief look at the code and it seems to me that one should be able to just add a parameter to the node and then use that where the paths gets formed. I'm probably missing something more fundamental?

I would like multiple maps so I can have one that shows the last N tracks full-screen and a separate map that I'd like to embed into the dashboard UI that shows a single track that I'd like to edit. I wouldn't look at both at the same time, but it gets messy if I have to reconfigure the maps depending on what gets requested.

**Comment by dceejay** [comment]
feel free to show me how.

**Comment by tve** [comment]
I did a first cut: https://github.com/tve/RedMap/commit/b725c17a48df9c6d7e1a7844665f69069df3b0ce
It seems to work so far. The ctrl-shift-M tips need to be fixed and the worldmap-in node's socket also needs fixing, which is non-trivial. I'm thinking that I'll have it create a callback if the socket doesn't exist such that when the corresponding worldmap node gets created the callback gets invoked.

**Comment by tve** [comment]
I also fixed the worldmap-in nodes: https://github.com/tve/RedMap/commit/7803b9a01adbf67ebe72eb31b02b1d1b626614be

I can prep a PR, if this stuff looks like the right way to go. I have a number of doubts:
- Why is there a worldmap-in node as opposed to simply giving each worldmap node an output? That seems to be the way, for example, the dashboard UI nodes work. Not having a separate node avoids corner cases where the worldnamp-in node has a different name from the worldmap node, or there are multiple worldmap-in nodes for one worldmap node.
- I don't like the checkbox I added to choose whether a worldmap node should use the default URI path or a custom path, primarily because it creates more corner cases that don't work properly. Ideally, if name is blank then it's the default/legacy /worldmap and if it's filled in then it's /worldmaps/{{name}}. But that is not backwards compatible. Thoughts?

**Comment by dceejay** [comment]
close... Why not just add a uri field (maybe called Path) just above the Name field (in HTML file) and default it to /worldmap then in js file  `this.uri = n.uri || "/worldmap";` etc...
In html can also add and oneditprepare taht check if field is empty and forces it to /worldmap - which then handles older versions "migrating".

Reason for the in node was that the Node-RED look and feel style tries to end flows when things go out - and start with things coming in... otherwise everything "is in the middle"... and a lot of times you don't need the in node either.  

If you add the same path field as per above to the in then that would/should be fine shouldn't it ?

The "other" way would be to add the websocket as a config node within the node - and then share that between the in and out nodes... but that's probably over the top.

**Comment by tve** [comment]
Yes, it's still on my to-do list, but if you don't have a PR by tomorrow feel free to grab the diffs and munge them.

**Comment by dceejay** [comment]
Thanks - happy for your input. Def keeping things moving.

**Comment by dceejay** [comment]
First effort - in branch multimap
https://github.com/dceejay/RedMap/tree/multimap

Need to think what to do re keyboard shortcut.
And also there doesn't seem to be a way to clean up express static routes - so if you change the path then the html side of the old one remains valid until you restart Node-RED.

**Comment by dceejay** [comment]
Going to ignore/leave the keyboard shortcut problem for now and assume most people won't actually change the default endpoint very much.... :-)
